# numpy基本操作

In [1]:
import numpy

In [17]:
vector = numpy.array([5,10,15,20])
matrix = numpy.array([[5,10,15],[20,25,30]])
print(vector)
print(matrix)

[ 5 10 15 20]
[[ 5 10 15]
 [20 25 30]]


In [19]:
print(vector.shape)
print(matrix.shape)

(4,)
(2, 3)


In [21]:
vector = numpy.array([5,10,15,20.0])
vector.dtype

dtype('float64')

In [34]:
print(vector[0:2])
print(matrix[:,1])
print(matrix[:2,1:2])

[  5.  10.]
[10 25]
[[10]
 [25]]


In [26]:
print(help(numpy.genfromtxt))
input = numpy.genfromtxt('localhost.txt',delimiter=',',dtype=str,skip_header=1)
print(input)
print(type(input))

[['892' '3' 'Kelly' 'male']
 ['893' '3' 'Wilkes' 'female']
 ['894' '2' 'Myles' 'male']
 ['895' '3' 'Wirz' 'male']]
<class 'numpy.ndarray'>


In [30]:
print(input[0,2])
print(input[1,2])

Kelly
Wilkes


In [35]:
vector = numpy.array([5,10,15,20])
vector == 10

array([False,  True, False, False], dtype=bool)

In [41]:
index = (vector == 10) | (vector == 5)
print(vector[index])

[ 5 10]


In [46]:
vector = numpy.array(["5","10","15","20"])
print(vector.dtype)
print(vector)
vector = vector.astype(float)
print(vector.dtype)
print(vector)
print(vector.min())

<U2
['5' '10' '15' '20']
float64
[  5.  10.  15.  20.]
5.0


In [49]:
matrix = numpy.array([[5,10,15],[20,25,30],[35,40,45]])
print(matrix.sum(axis=1))
print(matrix.sum(axis=0))

[ 30  75 120]
[60 75 90]


In [50]:
import numpy as np

In [55]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [56]:
a.shape

(3, 5)

In [63]:
print(help(np.ndim))
print(a.ndim)
print(a.dtype.name)
print(a.size)

2
int64
15


# numpy初始化与操作

In [66]:
np.zeros((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [71]:
np.ones((2,3,4),dtype=np.int32)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

10-15之间我们每隔0.5取一个数

In [74]:
np.arange(10,15,0.5)

array([ 10. ,  10.5,  11. ,  11.5,  12. ,  12.5,  13. ,  13.5,  14. ,  14.5])

调取random模块的random函数得到2行3列的矩阵

In [76]:
np.random.random((2,3))

array([[ 0.41267942,  0.28269372,  0.46680873],
       [ 0.44050161,  0.76351182,  0.82839201]])

0-pi之间，我们平均一共取50个数

In [77]:
from numpy import pi
np.linspace(0,pi,50)

array([ 0.        ,  0.06411414,  0.12822827,  0.19234241,  0.25645654,
        0.32057068,  0.38468481,  0.44879895,  0.51291309,  0.57702722,
        0.64114136,  0.70525549,  0.76936963,  0.83348377,  0.8975979 ,
        0.96171204,  1.02582617,  1.08994031,  1.15405444,  1.21816858,
        1.28228272,  1.34639685,  1.41051099,  1.47462512,  1.53873926,
        1.60285339,  1.66696753,  1.73108167,  1.7951958 ,  1.85930994,
        1.92342407,  1.98753821,  2.05165235,  2.11576648,  2.17988062,
        2.24399475,  2.30810889,  2.37222302,  2.43633716,  2.5004513 ,
        2.56456543,  2.62867957,  2.6927937 ,  2.75690784,  2.82102197,
        2.88513611,  2.94925025,  3.01336438,  3.07747852,  3.14159265])

In [85]:
a = np.array([5,10,15,20])
b = np.arange(4)
print(np.exp(b))
print(np.sqrt(b))
print("----------------------------------------------")
c = a - b
print(c)
print(c-1)
print(c**2)
print(c<10)

[  1.           2.71828183   7.3890561   20.08553692]
[ 0.          1.          1.41421356  1.73205081]
----------------------------------------------
[ 5  9 13 17]
[ 4  8 12 16]
[ 25  81 169 289]
[ True  True False False]


In [83]:
a = np.array([[1,1],
              [0,1]])
b = np.array([[2,1],
              [1,2]])
print(a*b)
print(a.dot(b))
print(np.dot(a,b))

[[2 1]
 [0 2]]
[[3 3]
 [1 2]]
[[3 3]
 [1 2]]


In [91]:
a = np.floor(10*np.random.random((3,4)))
print(a)
print("----------------------------------------------")
print(a.ravel())
print("----------------------------------------------")
a.shape = (6,2)
print(a)
print("----------------------------------------------")
print(a.T)

[[ 7.  0.  4.  6.]
 [ 2.  8.  5.  3.]
 [ 1.  3.  0.  7.]]
----------------------------------------------
[ 7.  0.  4.  6.  2.  8.  5.  3.  1.  3.  0.  7.]
----------------------------------------------
[[ 7.  0.]
 [ 4.  6.]
 [ 2.  8.]
 [ 5.  3.]
 [ 1.  3.]
 [ 0.  7.]]
----------------------------------------------
[[ 7.  4.  2.  5.  1.  0.]
 [ 0.  6.  8.  3.  3.  7.]]


In [94]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print(a)
print(b)
print("----------------------------------------------")
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[ 7.  6.]
 [ 6.  4.]]
[[ 7.  6.]
 [ 0.  9.]]
----------------------------------------------
[[ 7.  6.]
 [ 6.  4.]
 [ 7.  6.]
 [ 0.  9.]]
[[ 7.  6.  7.  6.]
 [ 6.  4.  0.  9.]]


In [97]:
a = np.floor(10*np.random.random((2,12)))
print(np.hsplit(a,3))
print("----------------------------------------------")
print(np.hsplit(a,(3,4)))

[array([[ 3.,  1.,  7.,  8.],
       [ 5.,  6.,  1.,  7.]]), array([[ 2.,  6.,  8.,  3.],
       [ 9.,  4.,  8.,  4.]]), array([[ 2.,  9.,  9.,  2.],
       [ 3.,  3.,  0.,  1.]])]
----------------------------------------------
[array([[ 3.,  1.,  7.],
       [ 5.,  6.,  1.]]), array([[ 8.],
       [ 7.]]), array([[ 2.,  6.,  8.,  3.,  2.,  9.,  9.,  2.],
       [ 9.,  4.,  8.,  4.,  3.,  3.,  0.,  1.]])]


In [98]:
a = np.floor(10*np.random.random((12,2)))
print(np.vsplit(a,3))
print("----------------------------------------------")
print(np.vsplit(a,(3,4)))

[array([[ 0.,  9.],
       [ 1.,  2.],
       [ 2.,  4.],
       [ 5.,  5.]]), array([[ 0.,  5.],
       [ 1.,  4.],
       [ 2.,  6.],
       [ 2.,  1.]]), array([[ 1.,  7.],
       [ 0.,  8.],
       [ 9.,  5.],
       [ 8.,  5.]])]
----------------------------------------------
[array([[ 0.,  9.],
       [ 1.,  2.],
       [ 2.,  4.]]), array([[ 5.,  5.]]), array([[ 0.,  5.],
       [ 1.,  4.],
       [ 2.,  6.],
       [ 2.,  1.],
       [ 1.,  7.],
       [ 0.,  8.],
       [ 9.,  5.],
       [ 8.,  5.]])]


复制

a = b 那么两个除了变量名不一样，指向同一地址值

view不再指向同一地址,但是c的值改变会导致a的值跟着变

我们如果复制使用copy，不再指向同一地址,d的值改变也不会导致a的值跟着变

In [99]:
c = a.view()
print(id(a))
print(id(c))

4557508736
4557548240


In [100]:
d = a.copy()
print(id(a))
print(id(d))

4557508736
4557510176


In [106]:
a = np.arange(0,20,5)
b = np.tile(a,(2,3))
print(b)

[[ 0  5 10 15  0  5 10 15  0  5 10 15]
 [ 0  5 10 15  0  5 10 15  0  5 10 15]]


取矩阵最大值

In [101]:
data = np.sin(np.arange(20).reshape(5,4))
print(data)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]


In [119]:
index = data.argmax(axis=0)
print(index)
data_max = data[index,range(data.shape[1])]
print(data_max)

[2 0 3 1]
[ 0.98935825  0.84147098  0.99060736  0.6569866 ]


In [123]:
a = np.array([[4,3,5],[4,1,4]])
np.sort(a,axis=1)

array([[3, 4, 5],
       [1, 4, 4]])

In [124]:
np.argsort(a)

array([[1, 0, 2],
       [1, 0, 2]])